# Generated by Django 3.2 on 2022-05-11 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receita_publicado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='publicado',
            new_name='publicada',
        ),
    ]
